---
title: "Exploratory Analysis of Oregon Hospitals 2006-2014"
author: "Dave Straube"
date: "March 21, 2016"
output: pdf_document
---

This document presents an exploratory analysis of Oregon hospital trends based on publicly available data provided by 
the Oregon Health Authority.

# Data Cleaning

Annual Excel format files for 2006 through 2014 
were downloaded from the Oregon Health Authority [here](https://www.oregon.gov/oha/OHPR/RSCH/pages/hospital_reporting.aspx).
A new sheet was created in each file which contained a copy of the original data but with common column names.
This new sheet was exported
in CSV format and then read into R where all subsequent cleaning and analysis was performed. Several issues were noted
and remedied as follows:

* Inconsistent hospital names - some due to ownership changes, others due to human variability. Cleaned data maps 
all hospital names to their 2014 equivalent.

* Inconsistent column names - remedied by hand in Excel.

* Missing columns:

    + `Other Operating Revenue` missing from early years was calculated as `Total Operating Revenue` minus
`Net Patient Revenue`.

    + Later years were missing `Charity Care`, `Bad Debt`, and `Total Uncompensated Care` as a percentage of
`Gross Patient Revenue`. This was calculated for all years as the respective value divided by `Gross Patient Revenue`.

    + Several years were missing the `Type` (A, B, or DRG) column. When missing, `Type` was assigned as the previous year's `Type`.

* Year 2010 separated hospital financial data and uncompensated care into two sheets. This was manually combined when
generating the sheet with common column names.

* `Total Margin` was sometimes a calculated value and sometimes a hardcoded value. When calculated, different years
used different formulas! As a result, all `Total Margin` data was ignored and a value calculated using
`Net Income / (Total Operating Revenue + Net Non-Operating Revenue)`.

Most of the data in the original spreadsheets was hardcoded despite the fact that certain columns clearly are derived 
from others. This leaves room for both transcription and calculation error. We checked the data against the following 
rules. The number in parenthesis following each rule identifies how many rows (of 514 total) failed the rule. Rules were
devised based on definitions provided in the 2014 spreadsheet. Those definitions are appended to this document.

* `Total Operating Revenue = Net Patient Revenue + Other Operating Revenue` (4)

* `Operating Income = Total Operating Revenue - Total Operating Expenses` (4)

* `Operating Margin = Operating Income / Total Operating Revenue` (3)

* `Net Income = Operating Income + Net Non-operating Revenue` (3)

* `Total Uncompensated Care = Charity Care + Bad Debt` (0)

\textcolor{red}{These errors and several NA cases are present in the current exploratory analysis and should be remedied
prior to final analysis and public consumption.} See section titled _Data Errors_ for full detail on these errors.

# Exploratory Analysis

```{R, echo = FALSE}
source("./explore.R")
```

The focus of exploratory analysis was to investigate how hospital profitability might have changed due to the introduction
of the Affordable Care Act. We first look at uncompensated care levels over time. As dollar values are affected
by the number of individuals served, which in turn is affected by enrollments, we normalize by showing uncompensated care as a
percentage of gross patient revenue.

This plot shows charity care as a percentage of gross patient revenue.

```{R, echo = FALSE, fig.width = 7, fig.height = 3}
pl.cc.as.pct.of.gpr
```

This plot shows bad debt as a percentage of gross patient revenue.

```{R, echo = FALSE, fig.width = 7, fig.height = 3}
pl.bd.as.pct.of.gpr
```

The previous two plots show that most hospitals followed the same trend with regards to charity care and bad debt,
both of which decreased dramatically in 2013. 
The next plot examines this trend by hospital type - namely A, B, or DRG. The pink 
vertical column represents the recent _Great Recession_ as per the
[St. Louis Federal Reserve Bank](https://research.stlouisfed.org/fred2/help-faq/) and the black vertical line represents the
ACA's enactment date of 3/23/2010. Bad debt and charity care are identified by color with their sum representing total
uncompensated care.

```{R, echo = FALSE, fig.width = 7, fig.height = 5}
pl.uc.mean.as.pct.of.gpr
```

The plots show that both bad debt and charity care dropped in 2013 for all types of hospitals
with bad debt falling more steeply. Pre-2013 the total uncompensated care contour seems to be defined mostly
by the charity care contour with bad debt a near constant percentage.

The next plot shows how operating margins (dashed line) and total margins (solid line) have changed over time. As before,
we plot mean values by type of hospital.

```{R, echo = FALSE, fig.width = 7, fig.height = 3}
pl.mean.margins
```

We note that total margins are consistently larger than operating margins but that there is no common post-ACA trend
for all hospital types. The simplistic reason why total margins are consistently higher than operating margins is that
total margins include net non-operating revenue (investments and tax revenues as per the definitions at the end of
this document) while operating margins do not.

The last plot is intended to show how much hospital income comes from non-operating sources and
to highlight the relative revenue sizes among hospital types.
Recall that `Net Income` is the sum of `Operating Income` and `Net Non-operating Revenue` where the latter is defined as "investments and tax revenue." Either
component can be negative in a given year. When both components are positive or both components negative, then their stacked
values in the plot represent their sum, i.e. net income. When only one component is negative, then net income is not
directly shown by the plot and instead would be the sum of the negative and positive components. Whichever component is
larger determines whether net income was positive or negative for the year.

```{R, echo = FALSE, fig.width = 7, fig.height = 6}
suppressWarnings(print(pl.net.income))
```

The plot shows that some
type A hospitals generate 50% or more of their net income from nonoperating revenue - see for example years
2010 and 2011. The outliers are probably greater than 50% since the plot only showed mean values for the hospital type.
Post-ACA non-operating revenue seems to be a fairly constant percentage for DRG hospitals, but still averaging 15% or higher.
Lastly, in the post-ACA timeframe net income has been dropping for type A hospitals, fluctuated for type B hospitals,
and grown for type DRG hospitals. Lacking annual patient counts one can not say how much the DRG gain is due to pricing 
versus volume.

# Data Errors

This section lists data errors discovered during data cleaning.

```{R, echo = FALSE}
source("./getdata.R")
```

